ygowthamr/WhitePaper

templates/notesapp/login.html
templates/notesapp/main.html
templates/notesapp/signup.html

Closes #2 
Description:
1. Made redirection to index page from login and signup page when user is not logged in.
2. When user is logged in added a scroll to top using the navbar keeping the header sticky to the body in main.html. To keep it sticky added an inline css and to make a scroll to top effect added an in body script.

Made notepad logo clickable from every possible page

---

static/javascript/script.js
templates/notesapp/main.html

Closes #9 
Added a javascript function that prevents adding empty notes. It shows a message to add note in the textbox itself that persists for 2 seconds only.
https://github.com/user-attachments/assets/906421ff-0fd2-47ec-b3f3-22f50eae42fe

Prevent Empty Note Creation in Notepad Form

---

static/javascript/script.js
templates/notesapp/index.html

📋 Description
Fix issue #3 
The function implementation was correct but lacked the addBtn ID for the "Add it" button. I addressed the text "Please write something to add a note" by adding it as a placeholder instead of a value in the code. If the input is empty, notes will not be added, and unnecessary code has been removed.
🔨 Changes Made
Removed unnecessary code, which was intended as a placeholder.
I added the ID to resolve the button issue.
Fixes #3

fix issue #3: Add It Button Functionality on Index Page

---

templates/notesapp/signup.html

This PR resolves an issue where the Login link on the signup page redirects to an incorrect route. The route has been updated to ensure it navigates users to the appropriate login page.
---
1. ✅ Located and updated the problematic Login link to point to the correct route.  
2. ✅ Verified the updated navigation works as expected without errors.  
3. ✅ Tested link functionality across browsers and device resolutions.  
4. ✅ Checked for broken links or redirection loops across the project.  
5. ✅ Ensured changes adhere to project guidelines and tested affected functionality thoroughly.  
6. 
---
Closes #5

Change Route of Login Link on Signup Page #5 #12

---

accounts/views.py
templates/notesapp/signup.html

Closes #23 
- Added login through route to prevent it from getting errors on deployment environment.
- And fixed broken redirection from Signup page, previously after Signup users got redirected to Error page so fixed that to return to login page after signup.

Added login through route and fixed redirection after signup to login page

---

static/javascript/script.js

- Fix Issue #4 
**Description**
Improved the search functionality and added exception case as no result found for searching the notes in the app
**Changes in this PR:**
---
Ensure the following before submitting your PR:

fix issue #4: Improvement in the Search Functionality

---

accounts/views.py
static/javascript/script.js
templates/notesapp/login.html
templates/notesapp/signup.html

Fix Issue #19 
**Description**
This pull request implements form validation for the signup process and ensures error messages are displayed appropriately in the following scenarios:
1. **Empty Fields:** Validation for required fields (First Name, Last Name, Email, Password, and Confirm Password).
2. **Password Mismatch:** Ensures the password and confirmation password match, with a red error message displayed.
3. **User Already Exists:** Displays an error if the email is already registered.
4. **Email Validation:** Ensures the email entered is in a valid format.
5. Additionally, error messages are styled in red for better visibility.
6. Resolved ID issue: Each input now has a unique ID and placeholder. At first all input field given same Id as "email" which is misleading
**Changes in this …

fix issue #19:  ADD form Validation

---

static/css/style.css
templates/notesapp/index.html
templates/notesapp/login.html
templates/notesapp/main.html
templates/notesapp/signup.html

This pull request addresses adding footer with dynamic year.
1. **Dynamic Copyright Year**: Displays the current year dynamically using JavaScript, ensuring that the year is always up-to-date on each page load.
2. **Footer Alignment**: The footer is aligned at the bottom of the page, ensuring that the footer stays at the bottom of the page regardless of content length, making the app more visually appealing and structured.
3. **Responsive Design**: Made the footer fully responsive so that it looks great on both mobile and desktop devices. Adjusted the font size for readability across different screen sizes.
- View the page in different screen sizes (desktop, tablet, mobile) and confirm that the footer:
- Always remains at the bottom of the page.
- Displays the correct current year …

Added the simple footer #29

---

MyNotepad/middleware.py
MyNotepad/settings.py
accounts/urls.py
accounts/views.py
notes/views.py
notesapp/views.py
static/javascript/script.js
templates/notesapp/main.html

1. **Session Management with Storage**
2. **Session Expiration Policies**
3. **Secure Cookies**
4. **Session Validation Middleware**
5. **Logout Functionality**
Resolves Issue #17

#17 Add sessions in app 

---

static/javascript/script.js
templates/notesapp/index.html

sorting using modification date will be applicable once edit feature is used.

Issue-#39_Added sorting feature

---

accounts/urls.py
accounts/views.py
notes/urls.py
notes/views.py
notesapp/views.py
static/javascript/authenticated.js
static/javascript/script.js
templates/notesapp/index.html
templates/notesapp/main.html

Notes created by users are saved in memory and not in the database. This results in the loss of notes after refreshing the page or logging out and logging back in.
This PR resolves the issue by ensuring that notes are properly saved in the database. The changes modify the logic to persist notes for authenticated users and retrieve them upon logging back in, ensuring data retention and better functionality.

#45 Notes are now saved in database.

---

static/javascript/authenticated.js
static/javascript/autosave.js
templates/notesapp/index.html
templates/notesapp/main.html

**Resolves #37** 
This PR aims to add auto save functionality while typing notes.

Implement autosave functionality 

---

requirements.txt

Fixes #53 . Setuptools version is updated!

Fixed bug in requirements.txt

---

MyNotepad/urls.py
accounts/urls.py
accounts/views.py
static/css/style.css
templates/notesapp/login.html
templates/notesapp/password_reset.html
templates/notesapp/reset_password.html

Closes : #18 
Added the Forget Password functionality.
1. Navigate to the password reset page.
2. Complete the OTP verification process.
3. Enter and confirm the new password.
4. Observe the redirection behavior after successful password reset.
5. Verify that the user is correctly redirected to the login page (`/accounts/login/`).
- Ensure that your Django server is running and static files are correctly loaded.
- Clear browser cache if redirection issues persist after applying this fix.
---

Add Forgot Password Functionality #18

---

MyNotepad/settings.py
MyNotepad/urls.py
accounts/urls.py
static/css/style.css
templates/notesapp/login.html
templates/notesapp/signup.html

Fix Issue #54: Added the login/signup via github oauth feature in new UI

---

README.md
requirements.txt

Closes: #74 
Readme file has been updated with the steps to setup GitHub OAuth login.
Required library to implement GitHub OAuth login has been added in the requirements file.
Now, the other devs will not have any problem setting up the project.

Updated the readme and requirements file

---

notes/urls.py
notes/views.py
static/javascript/authenticated.js
templates/notesapp/main.html
templates/notesapp/shared_note.html

This PR adds the ability for users to **share notes** with others via a **shareable link** or external platforms like **Email, WhatsApp, Twitter, LinkedIn**. Users can **generate unique links** to make their notes accessible while ensuring proper access control.  
- Closes #40  
- Added a **"Share"** button on each note.  
- Generated **unique shareable links** for each note.  
- Ensured **view-only access** for shared notes.  
- Integrated **external sharing options**, allowing users to share via **Email, WhatsApp, Twitter, LinkedIn**.  
- Implemented **proper validation and security checks** to ensure only authorized users can edit (if editing is enabled).  
https://github.com/user-attachments/assets/a7c8105e-7ce5-4198-9092-e8562e25a8a8
---
Hey @ygowthamr, kindly take a look at the …

Note Sharing Functionality

---

static/css/NewStyle.css
static/javascript/Theme.js
templates/notesapp/index.html
templates/notesapp/login.html
templates/notesapp/main.html
templates/notesapp/password_reset.html
templates/notesapp/reset_password.html
templates/notesapp/signup.html

Light & Dark theme functionality is done from my side
please let me know if anychange is required, closes issue #10

Added the toogle functionality

---

static/javascript/authenticated.js
static/javascript/script.js
templates/notesapp/main.html

#70 closes this issue
Update the css and script problem of notes card
Also notices the problem in edit button 
raising the new issue for the same
PLease assign that to me 
Also can u please keep it in hard section

Done with the notes card ui problem

---

static/javascript/authenticated.js
templates/notesapp/index.html
templates/notesapp/main.html

Added the text editor in the input section of the notes
#85

Added the Text Editor

---

MyNotepad/settings.py
static/javascript/authenticated.js
templates/notesapp/main.html

Fix issue #89 : Added copy to clipboard feature

---

static/javascript/script.js
templates/notesapp/index.html

Done with the functionality of the Home Page Save Notes 
Closes #88

Home Page Works Fine

---

README.md

#97
Hi @ygowthamr,
I am working on the SWOC task
This pull request adds a detailed project structure to the README file. The updated README now includes a section that outlines the directory structure of the WhitePaper project, making it easier for contributors and users to understand the organization of the project.
Changes include:
- Added a "Project Structure" section to the README.
- Detailed the directory and file structure of the project.

Add Project Structure to README

---

notes/urls.py
notes/views.py
static/javascript/authenticated.js
templates/notesapp/main.html

Fix Issue #28: Added the edit note feature for authenticated users

---

notes/urls.py
notes/views.py
static/javascript/authenticated.js
static/javascript/script.js
templates/notesapp/index.html

Done with print and text editor error
Closes:- #109 & #104

Done with print functionality and the error in text editor of index

---

static/javascript/authenticated.js
templates/notesapp/main.html
templates/notesapp/shared_note.html

Closes the issue:-
1. #117 
2. #113 
3. #116 
4. #105 
5. #100 
6. #118
Done with these all the functionalities. 
Attaching the vedio for the same:-
[Screen Recording - Made with FlexClip (30).webm](https://github.com/user-attachments/assets/31dd33d1-bc74-4620-976d-cb3c5fde5f08)

Done AI ChantBot, Image Functionalty, Share Via Short URL & QR Code , Vedio Functionality

---

static/javascript/authenticated.js
templates/notesapp/main.html

Added the ShortCut Keys And Pop Up OF it for the same...
Added the voice to text converter in the editor
closes: #122 & #114  & #103

Added the ShortCuts & Their Pop Up

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/custom_issue.md
.github/ISSUE_TEMPLATE/documentation_update.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/performance_issue.md
.github/ISSUE_TEMPLATE/question.md

Fixes #138 
Now the issue section has templates like:
Documentation Update
Bug Report
Feature Request
Custom Issue
Question / Help
Performance Issue

Fixes #138
